name: PyPI Release
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, closed]
env:
  CODACY_PROJECT_TOKEN: ${{secrets.CODACY_TOKEN}}
jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: |
          pytest

      - name: Publish
        env:
          TWINE_USERNAME: ${{ secrets.PLAT_JDP_ARTIFACTORY_USER }}
          TWINE_PASSWORD: ${{ secrets.PLAT_JDP_ARTIFACTORY_TOKEN }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --repository-url https://jdasoftware.jfrog.io/artifactory/api/pypi/pypi-local/ dist/* --verbose
